/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#9e3d00',
        'secondary-fixed': '#d3e4fe',
        'on-tertiary-container': '#fffbff',
        'secondary-container': '#d0e1fb',
        'on-primary-container': '#fefcff',
        'inverse-on-surface': '#eff0fc',
        'primary-container': '#076df6',
        'on-secondary': '#ffffff',
        primary: '#0056c6',
        'on-primary': '#ffffff',
        'surface-variant': '#e1e2ed',
        secondary: '#505f76',
        'inverse-surface': '#2d3039',
        'on-background': '#191b23',
        'surface-container-highest': '#e1e2ed',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'primary-fixed': '#d9e2ff',
        'outline-variant': '#c2c6d7',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#38485d',
        outline: '#727786',
        'tertiary-fixed-dim': '#ffb695',
        'on-secondary-container': '#54647a',
        'surface-container': '#ecedf9',
        'surface-container-high': '#e6e7f3',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8d9e5',
        'inverse-primary': '#b0c6ff',
        'on-surface': '#191b23',
        'on-secondary-fixed': '#0b1c30',
        background: '#faf8ff',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7c2e00',
        'surface-bright': '#faf8ff',
        'secondary-fixed-dim': '#b7c8e1',
        'tertiary-fixed': '#ffdbcc',
        'on-surface-variant': '#424655',
        'surface-container-low': '#f2f3ff',
        surface: '#faf8ff',
        'surface-tint': '#0058cb',
        'on-primary-fixed-variant': '#00429b',
        'tertiary-container': '#c64f00',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#b0c6ff',
        'on-primary-fixed': '#001945',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '24px',
        xs: '4px',
        xl: '32px',
        md: '16px',
        unit: '4px',
        gutter: '16px',
        lg: '24px',
        sm: '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
